# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  format_listener:
    rules:
      - { path: ^/, priorities: [json], fallback_format: json }
  view:
    view_response_listener: force
    formats:
      json: true
